# Generated by Django 5.2.5 on 2025-09-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POI',
            fields=[
                ('internal_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('poi_latitude', models.FloatField(blank=True, null=True)),
                ('poi_longitude', models.FloatField(blank=True, null=True)),
                ('avg_rating', models.FloatField(blank=True, null=True)),
                ('ratings', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
    ]
